### ISSUE TITLE
Wrong icon name in src/svg folder

### ISSUE THREAD

**Issue by pavlovator** [isneezy/open-weather-icons#5]
20d.svg should be named 50n.svg according to https://openweathermap.org/weather-conditions

**Comment by isneezy** [comment]
Hello @pavlovator thatnks for finding this out. could you issue a PR? I'll be very grateful.

**Comment by isneezy** [comment]
Fixed and released under [v0.0.8](https://github.com/isneezy/open-weather-icons/tree/v0.0.8)
